# Basic
title: 青龙沧歌
subtitle: 

description: 想说却还没说的还很多<br> 攒着是因为想写成歌<br> 让人轻轻的唱着 淡淡的记着<br> 就算终于忘了 也值了

# creator: <a href="http:/hellolzc.github.io">@hellolzc</a>
url: "http:/hellolzc.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 8
paginate_path: "page/:num/"

# Comment
comment:
    disqus: hellolzc
    # duoshuo: 
    
# Social
social:
    # weibo: onevcat
    github: hellolzc
    # twitter: onevcat
    mail: me@hellolzc.cn

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

# page.excerpt truncate characters
truncate_num: 200
